### ISSUE TITLE
Error in Rest20.GetPricingAsync(AccountId, parameters)

### ISSUE THREAD

**Issue by mszoke01** [mrchrisok/OandaV20.3#7]
Hello.  When I use the following code:

var AcctPairsList = new List<string>() { "AUD_JPY", "CAD_JPY", "CHF_JPY", "GBP_JPY", "NZD_JPY", "USD_JPY", "AUD_NZD", "AUD_USD", "USD_CAD", "USD_CHF", "USD_DKK", "USD_NOK", "USD_SEK", "GBP_USD", "NZD_USD" };
var parameters = new Rest20.PricingParameters() { instruments = AcctPairsList };
var AcctPrice = await Rest20.GetPricingAsync(AccountId, parameters);

I get the following error message.  

Input string '1000000.0' is not a valid integer. Path 'prices[7].bids[0].liquidity', line 1, position 3334.

Think I traced it to PriceBucket.cs line 16. public int liquidity { get; set; } should be decimal??

Let me know what you think.  Thanks.
Regards, 
Michael

**Comment by mrchrisok** [comment]
PriceBucket.liquidity has been updated to type: decimal
